import { Container } from 'react-bootstrap';
import Accordion from 'react-bootstrap/Accordion';

const AiFaqs = () => {
  return (
    <Container>
      <h1>AI Agents User&apos;s Manual and FAQ&apos;s</h1>
      <Accordion defaultActiveKey="0" flush>
        <Accordion.Item eventKey="0">
          <Accordion.Header>HOW TO USE IT </Accordion.Header>
          <Accordion.Body>
            <p>1. Enter a number of web reference in the search bar</p>
            <p>
              2. Enter Your{' '}
              <a href="https://platform.openai.com/">OpenAi API key</a>
            </p>
            <p>3. Enter the topic that you want to generate</p>
            <p>4. Click Generate Blog</p>
          </Accordion.Body>
        </Accordion.Item>
        <Accordion.Item eventKey="1">
          <Accordion.Header>FAQs Before Using It </Accordion.Header>
          <Accordion.Body>
            <p>
              <p className="fw-bolder">How does it work?</p> The Blog Post
              Generator uses web references from top ranking search engines to
              generate blog posts.
            </p>
            <p>
              <p className="fw-bolder">
                Is the information generated by the agent accurate?
              </p>{' '}
              The agent generates information based on the web references
              provided. It is recommended to verify the information generated.
            </p>
            <p>
              <p className="fw-bolder">How many web references can I use?</p>
              You can use a maximum of 10 web references.
            </p>
            <p>
              <p className="fw-bolder">How do I get an OpenAI API key?</p>
              You can get an OpenAI API key by signing up at{' '}
              <a href="https://platform.openai.com/">OpenAi</a>
            </p>
          </Accordion.Body>
        </Accordion.Item>
      </Accordion>
    </Container>
  );
};

export default AiFaqs;
